/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.telas;

import br.com.fatec.DAO.EstadiaDAO;
import br.com.fatec.VO.Cadastro_clientesVO;
import br.com.fatec.VO.EstadiaVO;
import br.com.fatec.VO.Reserva_quartoVO;
import br.com.fatec.auxiliar.Codemaker;
import br.com.fatec.conexao.Conexao;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author henrique
 */
public class Estadia extends javax.swing.JFrame {
    Conexao conexao = new Conexao();
    EstadiaDAO estadiaDAO = new EstadiaDAO(conexao);
    
    
    
    public void limparCampos(){
            txtCodEstadia.setText("");
            txtCpf.setText("");
            txtCodReserva.setText("");
            txtDataEntrada.setText("");
            txtNome.setText("");
            
    }

    /**
     * Creates new form Estadia
     */
    public Estadia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbCodigo1 = new javax.swing.JLabel();
        txtCodEstadia = new javax.swing.JTextField();
        lbCodigo2 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        btValidar = new javax.swing.JButton();
        lbCodigo3 = new javax.swing.JLabel();
        txtCodReserva = new javax.swing.JTextField();
        lbCodigo4 = new javax.swing.JLabel();
        txtDataEntrada = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbLogo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("Estadia");
        lbLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCodigo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCodigo.setText("CPF");

        txtNome.setEditable(false);

        lbCodigo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCodigo1.setText("Nome");

        txtCodEstadia.setEditable(false);

        lbCodigo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCodigo2.setText("Cod Estadia");

        btPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btValidar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btValidar.setText("Validar");
        btValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidarActionPerformed(evt);
            }
        });

        lbCodigo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCodigo3.setText("Cod Reserva");

        txtCodReserva.setEditable(false);

        lbCodigo4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCodigo4.setText("Data Entrada");

        txtDataEntrada.setEditable(false);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigo4)
                            .addComponent(lbCodigo2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodigo1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodigo)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCodigo3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(lbCodigo3)
                    .addComponent(txtCodReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo4)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo2)
                    .addComponent(txtCodEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(btValidar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        Reserva_quartoVO reserva_quartoVO = new Reserva_quartoVO();
        Cadastro_clientesVO cadastro_clientesVO = new Cadastro_clientesVO();
        EstadiaVO estadiaVO = new EstadiaVO(cadastro_clientesVO, reserva_quartoVO);
        String cpf = txtCpf.getText();
        //estadiaVO.getCliente().setCpf(txtCpf.getText());
        //cadastro_clientesVO.setCpf(txtCpf.getText());
        estadiaVO.setCliente(cadastro_clientesVO);
        
        try {
            estadiaVO = estadiaDAO.pesquisarPK(cpf);
            /*if (estadiaVO == null){
                JOptionPane.showMessageDialog(rootPane, "Dados nao encontrados!",
                    "Mensagem ao Usuário", 
                    JOptionPane.INFORMATION_MESSAGE);}*/
           // else {
                    txtCpf.setText(estadiaVO.getCliente().getCpf());
                    txtNome.setText(estadiaVO.getCliente().getNome());
                    String codEstadia = (Codemaker.getCodigo());
                    //txtCodEstadia.setText(codEstadia);
                   // estadiaVO.setCodEstadia(codEstadia);
                if (estadiaVO.getReserva().getCodreserva() != null){
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                     String dateString;
                    dateString = sdf.format(estadiaVO.getReserva().getDataEntrada());
                    txtCodReserva.setText(estadiaVO.getReserva().getCodreserva());
                    txtDataEntrada.setText(dateString);
                    estadiaVO.setCodEstadia(codEstadia);
                    txtCodEstadia.setText(codEstadia);
                    
                } else {
                if(estadiaVO.getCliente().getNome()!= null && estadiaVO.getReserva().getCodreserva() == null){
                    Date dataatual = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                     String dateString;
                    dateString = sdf.format(dataatual);
                    txtCodReserva.setText("Não há reserva para este CPF");
                    txtDataEntrada.setText(dateString);
                    estadiaVO.setCodEstadia(codEstadia);
                    txtCodEstadia.setText(codEstadia);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Dados nao encontrados!",
                    "Mensagem ao Usuário", 
                    JOptionPane.INFORMATION_MESSAGE);
                 }
                }
            }
            
            
         catch (SQLException ex) {
            Logger.getLogger(Estadia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidarActionPerformed
         
        
         
        
        Reserva_quartoVO reserva_quartoVO = new Reserva_quartoVO();
        Cadastro_clientesVO cadastro_clientesVO = new Cadastro_clientesVO();
        EstadiaVO estadiaVO = new EstadiaVO(cadastro_clientesVO, reserva_quartoVO);
        
          
          
        String strData = txtDataEntrada.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        java.util.Date dataUtil = null;
        try {
            dataUtil = sdf.parse(strData);
        } catch (ParseException ex) {
            Logger.getLogger(Reserva_quarto.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date dataEntradaSql;
        dataEntradaSql= new java.sql.Date(dataUtil.getTime());
        
          
          
          cadastro_clientesVO.setNome(txtNome.getText());
            estadiaVO.setCliente(cadastro_clientesVO);
            
            cadastro_clientesVO.setCpf(txtCpf.getText());
            estadiaVO.setCliente(cadastro_clientesVO);
            
            reserva_quartoVO.setCodreserva(txtCodReserva.getText());
            estadiaVO.setReserva(reserva_quartoVO);
            
            reserva_quartoVO.setDataEntrada(dataEntradaSql);
            estadiaVO.setReserva(reserva_quartoVO);
            
            estadiaVO.setCodEstadia(txtCodEstadia.getText());
            
 
          
          
        try {
            estadiaDAO.cadastrar(estadiaVO);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
      limparCampos();
    }//GEN-LAST:event_btValidarActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
       /* Reserva_quartoVO reserva_quartoVO = new Reserva_quartoVO();
        Cadastro_clientesVO cadastro_clientesVO = new Cadastro_clientesVO();
        EstadiaVO estadiaVO = new EstadiaVO(cadastro_clientesVO, reserva_quartoVO);
        String cpf = txtCpf.getText();
        //estadiaVO.getCliente().setCpf(txtCpf.getText());
        cadastro_clientesVO.setCpf(txtCpf.getText());
        estadiaVO.setCliente(cadastro_clientesVO);
        
        try {
            estadiaVO = estadiaDAO.pesquisarPK(cpf);
            if (estadiaVO == null){
                JOptionPane.showMessageDialog(rootPane, "Dados nao encontrados!",
                    "Mensagem ao Usuário", 
                    JOptionPane.INFORMATION_MESSAGE);}
            else {
                    txtCpf.setText(estadiaVO.getCliente().getCpf());
                    txtNome.setText(estadiaVO.getCliente().getNome());
                    JOptionPane.showMessageDialog(null,estadiaVO.getCliente().getNome());
                    txtCodEstadia.setText(Codemaker.getCodigo());
                if (estadiaVO.getReserva().getCodreserva() != null){
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
                     String dateString;
                    dateString = sdf.format(estadiaVO.getReserva().getDataEntrada());
                    txtCodReserva.setText(estadiaVO.getReserva().getCodreserva());
                    txtDataEntrada.setText(dateString);
                    
                } else{
                    Date dataatual = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
                     String dateString;
                    dateString = sdf.format(dataatual);
                    txtCodReserva.setText("Não há reserva para este CPF");
                    txtDataEntrada.setText(dateString);
                } 
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Estadia.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_txtCpfFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao.setNomeBanco("Hotel");
        conexao.setPorta(3306);
        conexao.setSenha("");
        conexao.setServidor("localhost");
        conexao.setUsuario("root");          // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
new Menu_principal().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btValidar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbCodigo3;
    private javax.swing.JLabel lbCodigo4;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTextField txtCodEstadia;
    private javax.swing.JTextField txtCodReserva;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
